// examples/react/src/components/button.tsx
import React from 'react';

export interface ButtonProps {
  onClick?: React.MouseEventHandler<HTMLElement>;
  children?: React.ReactNode;
  forRealUnCoveredProps?: boolean;
}

// eslint-disable-next-line @typescript-eslint/no-empty-function
const noop = () => {};

const Button: React.FC<ButtonProps> = (props) => {
  // for coverage report some line are not covered
  if (props.forRealUnCoveredProps) {
    noop();
  } else {
    noop();
  }
  return (
    <button onClick={props.onClick} style={{ width: 200 }}>
      {props.children}
    </button>
  );
};

export default Button;

// examples/vue/src/components/button.vue
<template>
  <button @click="onClick" :style="{ width: '200px' }">
    <slot>123</slot>
  </button>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const props = defineProps<{
  onClick?: Function;
  forRealUnCoveredProps?: boolean;
}>();

// eslint-disable-next-line @typescript-eslint/no-empty-function
const noop = () => {};

// for coverage report some line are not covered
if (props.forRealUnCoveredProps) {
  noop();
} else {
  noop();
}
</script>
